Tests: avoid almostPlugin on CYGWIN
On CYGWIN, the build process of almostPlugin fails with this error:

qtbase/tests/auto/corelib/plugin/qpluginloader/almostplugin/CMakeFiles/almostplugin.dir/almostplugin.cpp.o: in function `AlmostPlugin::pluginName() const':
qtbase/tests/auto/corelib/plugin/qpluginloader/almostplugin/almostplugin.cpp:9.text+0x2c): undefined reference to `AlmostPlugin::unresolvedSymbol() const'
collect2: error: ld returned 1 exit status

This is correct, CYGWIN doesn't support that, like MinGW.
Attached patch fixes the error, according to the suggestions here:

Task-number: QTBUG-133778
Change-Id: I9fc261942200f62a5975cd91cb970472e5fca721
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>