Revert "QQuaternion: long live EulerAngles / eulerAngles()"
This reverts commit ba21e89c2f7b3e162cffa8a716ca3d835b8c9bd4.
Fortunately it only exists on dev.

Breaks build: <quote>

FAILED: src/xr/quick3dxr/CMakeFiles/Quick3DXr.dir/visionos/qquick3dxranchormanager_visionos.mm.o
...
/Users/qt/work/qt/qtquick3d/src/xr/quick3dxr/visionos/qquick3dxranchormanager_visionos.mm:122:41: error: call to 'fromEulerAngles' is ambiguous
122 |     static const QQuaternion s_rot90X = QQuaternion::fromEulerAngles({-90.0f, 0.0f, 0.0f});
    |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

</quote> or, as the submodule update 'bot (or possibly our internal AI
interpreter of the raw output) put it: <quote>

The compiler cannot decide which overload of fromEulerAngles to use
for the braced initializer list {-90.0f, 0.0f, 0.0f}. It identifies
two possible candidates from qquaternion.h:
* static QQuaternion fromEulerAngles(EulerAngles<float> angles)
* QQuaternion QQuaternion::fromEulerAngles(const QVector3D &angles)
This is a fatal compiler error that stopped the build.

</quote> It's possible a Q_WEAK_OVERLOAD can fix it, but I'd rather
wait for Marc to think about the best solution, so reverting.

Change-Id: I1102c5be703ebd8b76b49656d068147fd3a74695
Reviewed-by: Volker Hilsheimer <volker.hilsheimer@qt.io>