Revert renaming of QArrayData::ref_
This reverts part of commit 3f61f736266ece40d627dcf6214618a22a009fd1.
The renaming of the member caused Qt Creator to break. Since that was a
gratuitous change and was backported, it's hard to fix.

src/libs/utils/stringtable.cpp:97:44: error: ‘QArrayDataPointer<char16_t>::Data’ {aka ‘struct QTypedArrayData<char16_t>’} has no member named ‘ref_’; did you mean ‘ref’?

Pick-to: 6.10 6.9 6.8 6.5
Change-Id: I5d0b1a0c9b42adc38c7bfffd1a86e7abb08d952b
Reviewed-by: hjk <hjk@qt.io>
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
Reviewed-by: Fabian Kosmale <fabian.kosmale@qt.io>
Reviewed-by: Jarek Kobus <jaroslaw.kobus@qt.io>
Reviewed-by: Kai Köhne <kai.koehne@qt.io>