QSystemError: windowsComString - use UTF16-based QString literals
Unicode conversions aren't exactly cheap and require run-time
allocations. We can avoid them by using QString literals.

Change-Id: I8a40828bab24790dcca1214619e0fb3ec7d0bee9
Reviewed-by: Artem Dyomin <artem.dyomin@qt.io>
Reviewed-by: Pavel Dubsky <pavel.dubsky@qt.io>
Reviewed-by: Zhao Yuhang <2546789017@qq.com>