qlocale_win.cpp: Fix unity-build
Error after commit f039077830f41ca7ea7b1d91a4f7ad45a6613ea6:
.../qtbase/src/corelib/text/qlocale_win.cpp(745):
 error C2872: 'Windows': ambiguous symbol

C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\winrt\wrl/
client.h(927): note: could be 'Windows'

C:\Program Files (x86)\Windows Kits\10\include\10.0.26100.0\cppwinrt\
winrt/Windows.System.UserProfile.h(890): note: or 'winrt::Windows'

Amends 51e8d3592acc8bacf326fe3933b5dec13bb518e6

Change-Id: Ia32faa86bee6a284a5ad50ed82dcf8f08ab28dfd
Reviewed-by: Ivan Solovev <ivan.solovev@qt.io>