Drop now unused lambda capture
tokenProvider is unused inside the lambda since
638c9bd2595704606b53ba319c67568b479f9fc0,
triggering

        .../qt5/qtwayland/src/plugins/shellintegration/xdg-shell/qwaylandxdgshell.cpp:574:32: error: lambda capture 'tokenProvider' is not used [-Werror,-Wunused-lambda-capture]
          574 |                         [this, tokenProvider](const QString &token) {

in a local clang 19 build.

Pick-to: 6.9 6.8
Change-Id: I69f7884afee46859c66a46edce3e7a8001c60e22
Reviewed-by: David Edmundson <davidedmundson@kde.org>
Reviewed-by: David Redondo <qt@david-redondo.de>