QGenericUnixTheme: Fix build, adding missing #includes
qdbuslistener.cpp:105:5: error: ‘QJsonParseError’ was not declared in this scope
qgenericunixtheme.cpp:247:21: error: invalid use of incomplete type ‘class QDBusConnectionInterface’
qkdetheme.cpp:91:109: error: ‘QSettings’ was not declared in this scope; did you mean ‘QString’?
qkdetheme.cpp:712:30: error: ‘QStandardPaths’ has not been declared

Probably amends 53fb13456fffe8bfd192f9197c6d1703854b49a2.

Change-Id: I673a2fa3f34c162d4d76fffdf160ed8a7af1fc66
Reviewed-by: Joerg Bornemann <joerg.bornemann@qt.io>