Fix compilation of qtwebengine with sccache+clang+pch
Error was:

  fatal error: file '.../src/3rdparty/chromium/build/precompile.h' \
    has been modified since the precompiled header \
    'obj/cc/paint/paint/precompile.h-cc.gch' was built: mtime changed \
    (was 1765440170, now 1765463105)
  note: please rebuild precompiled header

Fixes: QTBUG-131650
Pick-to: 6.11 6.10 6.8 6.5
Change-Id: If3b46e7d3fc8e5aa9d26020fad962bffe604d590
Reviewed-by: Alexey Edelev <semlanik@gmail.com>