Fix compilation for VxWorks ARM64
VxWorks libc for Intel don't have implemented __extendhfxf2 function,
which can be emitted by compiler when converting float16 to 80-bit long
double. When checking Qt6 support for ARM64 it was found that the same
issue applies to ARM64, which causes similar compilation error
(Undefined reference to __extendhfxf2).

Fix this by adding exclusion to ARM64 when testing long double in
tst_qfloat16::ordering() test function.

Change-Id: Ia229677e551cb6d72762c16973dae23b270da7f7
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>