3rdparty: fix build if POSIX monitor wait states are unsupported
On CYGWIN, the build process fails at this point:

qtbase/src/corelib/io/../../3rdparty/forkfd/forkfd.c: In function ‘convertForkfdWaitFlagsToWaitFlags’:
qtbase/src/corelib/io/../../3rdparty/forkfd/forkfd.c:253:20: error: ‘WEXITED’ undeclared (first use in this function); did you mean ‘WIFEXITED’?
  253 |     int woptions = WEXITED;
      |                    ^~~~~~~
      |                    WIFEXITED
qtbase/src/corelib/io/../../3rdparty/forkfd/forkfd.c:253:20: note: each undeclared identifier is reported only once for each function it appears in
qtbase/src/corelib/io/../../3rdparty/forkfd/forkfd.c:255:21: error: ‘WNOWAIT’ undeclared (first use in this function)
  255 |         woptions |= WNOWAIT;
      |                     ^~~~~~~

The error itself is correct since CYGWIN doesn't support WEXITED and WNOWAIT.
Looking on top of the file, you can see this:

if !defined(WEXITED) || !defined(WNOWAIT)
  undef HAVE_WAITID
endif

So, testing HAVE_WAITID is can be good way for filtering this error.
Just before convertForkfdWaitFlagsToWaitFlags(), there is a block of
code, protected with a test checked by the preprocessor:

ifdef HAVE_WAITID
...
endif

so, I just moved that function in this control block for fixing the
issue.

Change-Id: Ia6dce926d1c8181cc0fb8dc8840d8982b37d80ca
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>