Corelib, fix runtime platform detection on CYGWIN
On CYGWIN, the build process fails at this point:

In file included from qtbase/src/corelib/global/qsysinfo.cpp:40:
qtbase/src/corelib/global/qoperatingsystemversion_win_p.h:19:10: fatal error: qt_windows.h: No such file or directory
   19 | #include <qt_windows.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

Besides the fact that qt_windows.h doesn't exist into the build
directory when compiling a POSIX-like platform, when compiling
under CYGWIN, the operating system is CYGWIN, not Windows.
So, it is better to collect those information by using Q_OS_UNIX
tools instead.

Change-Id: I496eedb58c4a3d1ce2da9fb3526a6ec5ed67f638
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>