QMetaObject: Add missing include for QSpan
This amends 67abb290be80024cd36cc4c78d4e74c3ff705dba
and fixes the following build error seen in a local clang
-no-pch build on Debian testing:

    [19/18766] Building CXX object qtbase/src/corelib/CMakeFiles/Core.dir/kernel/qobject.cpp.o
    FAILED: qtbase/src/corelib/CMakeFiles/Core.dir/kernel/qobject.cpp.o
    /usr/bin/ccache /usr/bin/clang++ -DBACKTRACE_HEADER=\"execinfo.h\" -DCore_EXPORTS -DELF_INTERPRETER=\"/lib64/ld-linux-x86-64.so.2\" -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_EXPLICIT_QFILE_CONSTRUCTION_FROM_PATH -DQT_LEAN_HEADERS=1 -DQT_MOC_COMPAT -DQT_NO_CAST_TO_ASCII -DQT_NO_CONTEXTLESS_CONNECT -DQT_NO_FOREACH -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_QASCONST -DQT_NO_QEXCHANGE -DQT_NO_QPAIR -DQT_NO_QSNPRINTF -DQT_NO_STD_FORMAT_SUPPORT -DQT_NO_USING_NAMESPACE -DQT_STRICT_QLIST_ITERATORS -DQT_TYPESAFE_FLAGS -DQT_USE_NODISCARD_FILE_OPEN -DQT_USE_QSTRINGBUILDER -D_GLIBCXX_ASSERTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I/home/michi/development/git/qt5/qtbase/src/corelib/Core_autogen/include -I/home/michi/development/git/qt5/qtbase/include -I/home/michi/development/git/qt5/qtbase/include/QtCore -I/home/michi/development/git/qt5/qtbase/src/corelib -I/home/michi/development/git/qt5/qtbase/src/corelib/global -I/home/michi/development/git/qt5/qtbase/src/corelib/kernel -I/home/michi/development/git/qt5/qtbase/src/corelib/../3rdparty/tinycbor/src -I/home/michi/development/git/qt5/qtbase/include/QtCore/6.11.0 -I/home/michi/development/git/qt5/qtbase/include/QtCore/6.11.0/QtCore -I/home/michi/development/git/qt5/qtbase/src/corelib/../3rdparty/forkfd -I/home/michi/development/git/qt5/qtbase/src/corelib/.rcc -I/home/michi/development/git/qt5/qtbase/mkspecs/linux-clang -isystem /usr/include/double-conversion -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -D_GLIBCXX_DEBUG -g -std=gnu++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Werror "-Wno-error=#warnings" -Wno-error=deprecated-declarations -Wno-error=deprecated-enum-enum-conversion -Wno-error=deprecated-copy-with-user-provided-copy -Wno-error=unused-but-set-variable -fcf-protection=full -ftrivial-auto-var-init=pattern -fstack-protector-strong -fexceptions -MD -MT qtbase/src/corelib/CMakeFiles/Core.dir/kernel/qobject.cpp.o -MF qtbase/src/corelib/CMakeFiles/Core.dir/kernel/qobject.cpp.o.d -o qtbase/src/corelib/CMakeFiles/Core.dir/kernel/qobject.cpp.o -c /home/michi/development/git/qt5/qtbase/src/corelib/kernel/qobject.cpp
    /home/michi/development/git/qt5/qtbase/src/corelib/kernel/qobject.cpp:3067:86: error: implicit instantiation of undefined template 'QSpan<const QArgumentType>'
     3067 |     int signal_index = QMetaObjectPrivate::indexOfSignalRelative(&smeta, signalName, signalTypes);
          |                                                                                      ^
    /home/michi/development/git/qt5/qtbase/src/corelib/tools/qcontainerfwd.h:32:89: note: template is declared here
       32 | template <typename T, std::size_t E = std::size_t(-1) /* = std::dynamic_extent*/> class QSpan;
          |                                                                                         ^

Pick-to: 6.10
Change-Id: I359f1d0fbc0cd15b8bcd8a3006b43ae0627752ed
Reviewed-by: Ahmad Samir <a.samirh78@gmail.com>