3rdparty: fix linking of cygQt6Core on CYGWIN
On CYGWIN, the final link of cygQt6Core process fails at this point:

qtbase/src/corelib/CMakeFiles/Core.dir/io/qprocess_unix.cpp.o:qprocess_unix.:(.rdata$.refptr.__interceptor_vfork[.refptr.__interceptor_vfork]+0x0): undefined reference to `__interceptor_vfork'
collect2: error: ld returned 1 exit status

so we just avoid that.

Change-Id: Iafe935981b507aa1449ed41e89fe6e86b9298dde
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>