xcb: mark parameters as unused with QT_NO_CLIPBOARD in QXcbDrag::setActionList
The build was failing with this error:

[...]/qxcbdrag.cpp: In member function ‘void QXcbDrag::setActionList(Qt::DropAction, Qt::DropActions)’:
[...]/qxcbdrag.cpp:575:45: error: unused parameter ‘requestedAction’ [-Werror=unused-parameter]
  575 | void QXcbDrag::setActionList(Qt::DropAction requestedAction, Qt::DropActions supportedActions)
      |                              ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
[...]/qxcbdrag.cpp:575:78: error: unused parameter ‘supportedActions’ [-Werror=unused-parameter]
  575 | void QXcbDrag::setActionList(Qt::DropAction requestedAction, Qt::DropActions supportedActions)
      |                                                              ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Amends cc1d891b8ed1c4f23183e4b06f46e5840a993e35.

Pick-to: 6.5 6.8 6.9 6.10
Change-Id: Ie4c8b425a1f07d062db242f962be3055a0e9db61
Reviewed-by: Liang Qi <liang.qi@qt.io>