Corelib: statvfs64 is unsupported on CYGWIN
On CYGWIN, the build process fails at this point:

In file included from qtbase/include/QtCore/6.9.0/QtCore/private/qcore_unix_p.h:1,
                 from qtbase/src/corelib/io/qstorageinfo_unix.cpp:11:
qtbase/src/corelib/io/qstorageinfo_unix.cpp:59:28: error: ‘::statvfs64’ has not been declared
   59 | #    define QT_STATFS    ::statvfs64
      |                            ^~~~~~~~~

This is correct, CYGWIN doesn't support that, although it provides support for large files.
Looking the code, you can see that also Haiku OS has the same behavior, so I just added an
additional test when defining QT_STATFSBUF and QT_STATFS

Change-Id: Ib250ccffc1a83e235a117b13b602194db617e75a
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>